version: 2

jobs:
  build:
    docker:
      - image: circleci/node:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: create zip
          command: |
            set -x
            mkdir dist
            zip dist/package.zip manifest.json index.js
      - store_artifacts:
          path: dist/

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker_config