name: package

on:
  push:
    branches:
      - master
    tags:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir package
          cp manifest.json package/
          cp index.js package/
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: package
